#!/bin/bash
set -e # stop on error

echo bulid client ...
yarn build
echo check out branch gh-pages ...
git checkout -b gh-pages
echo add build folder
git add -f build
echo commit changes
git commit -m "deploy to gh-pages"
echo push to remote gh-pages
git push origin `git subtree split --prefix build`:gh-pages --force
echo checkout branch master
git checkout master
echo delete branch gh-pages
git branch -D gh-pages
echo All done!